[build]
target = "aarch64-rpi.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.aarch64-rpi]
rustflags = ["-C", "link-arg=-Tlinker.ld", "-C", "prefer-dynamic=off"]
